-- Audit and compliance evidence linked to saved answers and annexure rows.
-- Converted from the legacy MariaDB evidence_master schema for PostgreSQL.

CREATE TABLE IF NOT EXISTS evidence_master (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    answer_id integer NOT NULL,
    annex_id integer NOT NULL DEFAULT 0,
    assesment_id integer NOT NULL,
    evi_type smallint NOT NULL,
    file_name varchar(56) NOT NULL,
    file_type smallint NOT NULL,
    description text NOT NULL DEFAULT '',
    emp_id integer NOT NULL,
    status_id smallint NOT NULL DEFAULT 0,
    review_emp_id integer NOT NULL DEFAULT 0,
    deleted_by_emp_id integer NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS idx_evidence_master_assessment_answer
    ON evidence_master (assesment_id, answer_id, annex_id, evi_type)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_evidence_master_assessment_status
    ON evidence_master (assesment_id, evi_type, status_id)
    WHERE deleted_at IS NULL;
